FROM postgres:14.3

# extend image to fit needs

#	Run command on PS:
#	docker run -it --rm --network some-network postgres psql -h some-postgres -U postgres
$ docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres
